name: Deploy Vite React to Vercel (Production)

on:
  push:
    branches:
      - master

env:
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Pull Vercel config
        run: vercel pull --yes --environment=production --token=$VERCEL_TOKEN

      - name: Build for production
        run: vercel build --prod --token=$VERCEL_TOKEN

      - name: Deploy to production
        run: vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
